/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Hamburger(props) {
  const { nodes, materials } = useGLTF('./models/hamburger.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.topBun.geometry}
        material={materials.bunMaterial}
        position={[0, 4.667, 0]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottomBun.geometry}
        material={materials.bunMaterial}
        position={[0, 0.683, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.meat.geometry}
        material={materials.meatMaterial}
        position={[0, 2.742, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.cheeseMaterial}
        position={[0.015, 3.14, -0.026]}
        scale={1.018}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottomBun001.geometry}
        material={materials.bunMaterial}
        position={[0, 0.683, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.plateMaterial}
        position={[0.015, -0.168, -0.026]}
      />
    </group>
  )
}

useGLTF.preload('./models/hamburger.glb')
