/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Pizza(props) {
  const { nodes, materials } = useGLTF('./models/pizza.glb')

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dough.geometry}
        material={materials.doughMaterial}
        position={[0.015, 0.463, -0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tomato.geometry}
        material={materials.tomatoMaterlial}
        position={[0.015, 1.853, -0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mozzarella.geometry}
        material={materials.mozzarellaMaterial}
        position={[3.126, 0.633, 1.962]}
        rotation={[-Math.PI, 0.81, -Math.PI]}
        scale={1.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.basil.geometry}
        material={materials.basilMaterial}
        position={[0.48, 0.743, 1.276]}
        rotation={[3.083, -0.297, -3.106]}
        scale={[1, 1, 2.014]}
      />
    </group>
  )
}

useGLTF.preload('./models/pizza.glb')
