name: Deploy
run-name: ${{ github.event.head_commit.message }}

on:
  push:
    branches-ignore:
      - main
      - 49-creating-a-scene-in-blender
      - 50-baking-and-exporting-the-scene
      - 51-importing-and-optimizing-the-scene
      - 52-adding-details-to-the-scene

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Vercel Link
        run: |
          VERCEL_PROJECT_NAME=$(echo "${{ github.ref }}" | sed -E 's@refs/heads/@@; s@/@-@g')
          echo "VERCEL_PROJECT_NAME=$VERCEL_PROJECT_NAME" >> $GITHUB_ENV
          vercel link --token=${{ secrets.VERCEL_TOKEN }} -p $VERCEL_PROJECT_NAME --yes
      - name: Add Domain
        run: |
          VERCEL_PROJECT_URL=$(echo "${{ github.actor }}-${{ env.VERCEL_PROJECT_NAME }}".vercel.app)
          vercel domains add $VERCEL_PROJECT_URL --token=${{ secrets.VERCEL_TOKEN }}
        continue-on-error: true
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
